apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: anyname
spec:
  replicas: 2
  selector:
    matchLabels:
      app: anyname
  template:
    metadata:
      labels:
        app: anyname
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080
